# Get the latest Ubuntu image
FROM ubuntu:latest
# Update the package list
RUN apt-get update
# Upgrade all installed packages
RUN apt-get upgrade -y
# Print "Hello, World!" to the terminal
CMD ["echo", "Hello, World!"]
